-- ── Dashboard (Start Menu) ───────────────────────────────
return {
  {
    "nvimdev/dashboard-nvim",
    event = "VimEnter",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    opts = {
      theme = "doom",
      config = {
        header = {
          "",
          "",
          "",
          "                                                       ",
          "                   ███████╗███████╗██████╗  ██████╗                      ",
          "                   ╚══███╔╝██╔════╝██╔══██╗██╔═══██╗                     ",
          "                     ███╔╝ █████╗  ██████╔╝██║   ██║                     ",
          "                    ███╔╝  ██╔══╝  ██╔══██╗██║   ██║                     ",
          "                   ███████╗███████╗██║  ██║╚██████╔╝                     ",
          "                   ╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝                     ",
          "                                                                ",
          "                         ⟨  N E O V I M  ⟩                              ",
          "",
          "",
        },
        center = {
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "Find File                        ",
            desc_hl = "String",
            key = "f",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Telescope find_files",
          },
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "New File                         ",
            desc_hl = "String",
            key = "n",
            key_hl = "Number",
            key_format = " [%s]",
            action = "ene | startinsert",
          },
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "Recent Files                     ",
            desc_hl = "String",
            key = "r",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Telescope oldfiles",
          },
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "Find Word                        ",
            desc_hl = "String",
            key = "g",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Telescope live_grep",
          },
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "File Explorer                    ",
            desc_hl = "String",
            key = "e",
            key_hl = "Number",
            key_format = " [%s]",
            action = "NvimTreeToggle",
          },
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "Config                           ",
            desc_hl = "String",
            key = "c",
            key_hl = "Number",
            key_format = " [%s]",
            action = "lua require('telescope.builtin').find_files({ cwd = vim.fn.stdpath('config') })",
          },
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "Restore Session                  ",
            desc_hl = "String",
            key = "s",
            key_hl = "Number",
            key_format = " [%s]",
            action = "lua require('persistence').load()",
          },
          {
            icon = "󰒲  ",
            icon_hl = "Title",
            desc = "Lazy Plugins                     ",
            desc_hl = "String",
            key = "l",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Lazy",
          },
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "Mason                            ",
            desc_hl = "String",
            key = "m",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Mason",
          },
          {
            icon = "  ",
            icon_hl = "Title",
            desc = "Quit                             ",
            desc_hl = "String",
            key = "q",
            key_hl = "Number",
            key_format = " [%s]",
            action = "qa",
          },
        },
        footer = function()
          local stats = require("lazy").stats()
          local v = vim.version()
          return {
            "",
            "⚡ " .. stats.loaded .. "/" .. stats.count .. " plugins loaded in " .. string.format("%.1f", stats.startuptime) .. "ms",
            "   v" .. v.major .. "." .. v.minor .. "." .. v.patch,
          }
        end,
      },
    },
  },
}
