-- ── Dashboard (Start Menu) ───────────────────────────────
return {
  {
    "nvimdev/dashboard-nvim",
    enabled = true,
    event = "VimEnter",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    opts = {
      theme = "doom",
      config = {
        header = {
          "",
          "",
          "",
          "                                                       ",
          "                   ███████╗███████╗██████╗  ██████╗                      ",
          "                   ╚══███╔╝██╔════╝██╔══██╗██╔═══██╗                     ",
          "                     ███╔╝ █████╗  ██████╔╝██║   ██║                     ",
          "                    ███╔╝  ██╔══╝  ██╔══██╗██║   ██║                     ",
          "                   ███████╗███████╗██║  ██║╚██████╔╝                     ",
          "                   ╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝                     ",
          "                                                                ",
          "                         ⟨  N E O V I M  ⟩                              ",
          "",
          "",
        },
        center = {
          {
            icon = "󰈞  ",
            icon_hl = "Title",
            desc = "Find file",
            desc_hl = "String",
            key = "f",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Telescope find_files",
          },
          {
            icon = "󰎔  ",
            icon_hl = "Title",
            desc = "New file",
            desc_hl = "String",
            key = "n",
            key_hl = "Number",
            key_format = " [%s]",
            action = "ene | startinsert",
          },
          {
            icon = "󰈙  ",
            icon_hl = "Title",
            desc = "Recent files",
            desc_hl = "String",
            key = "r",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Telescope oldfiles",
          },
          {
            icon = "󰈬  ",
            icon_hl = "Title",
            desc = "Find word",
            desc_hl = "String",
            key = "g",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Telescope live_grep",
          },
          {
            icon = "󰙅  ",
            icon_hl = "Title",
            desc = "File explorer",
            desc_hl = "String",
            key = "e",
            key_hl = "Number",
            key_format = " [%s]",
            action = "NvimTreeToggle",
          },
          {
            icon = "󰉋  ",
            icon_hl = "Title",
            desc = "Config",
            desc_hl = "String",
            key = "c",
            key_hl = "Number",
            key_format = " [%s]",
            action = "lua require('telescope.builtin').find_files({ cwd = vim.fn.stdpath('config') })",
          },
          {
            icon = "󰁯  ",
            icon_hl = "Title",
            desc = "Restore session",
            desc_hl = "String",
            key = "s",
            key_hl = "Number",
            key_format = " [%s]",
            action = "lua require('persistence').load()",
          },
          {
            icon = "󰒲  ",
            icon_hl = "Title",
            desc = "Lazy plugins",
            desc_hl = "String",
            key = "l",
            key_hl = "Number",
            key_format = " [%s]",
            action = "Lazy",
          },
          {
            icon = "󰐥  ",
            icon_hl = "Title",
            desc = "Quit",
            desc_hl = "String",
            key = "q",
            key_hl = "Number",
            key_format = " [%s]",
            action = "qa",
          },
        },
        footer = function()
          local stats = require("lazy").stats()
          local ms = (math.floor(stats.startuptime * 100 + 0.5) / 100)
          return { "⚡ Neovim loaded " .. stats.loaded .. "/" .. stats.count .. " plugins in " .. ms .. "ms" }
        end,
      },
    },
  },
}
